# Generated by Django 5.0.7 on 2024-08-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_task_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sub_tasks',
            field=models.ManyToManyField(blank=True, null=True, related_name='tasks', to='myapp.subtask'),
        ),
    ]
